### ISSUE TITLE
after executing any python program for mega pi from raspberry pi its only showing same thing follows

### ISSUE THREAD

**Issue by rohinipatare** [Makeblock-official/PythonForMegaPi#11]
root@raspberrypi:/home/pi# python stepperMotorRun.py 
init MegaPi
<megapi.mSerial instance at 0x766ce968>

I performed all the steps given for configuring a raspberry pi and mega pi but its showing same thing after executing any example program for mega pi

**Comment by vornet** [comment]
I had a similar issue and it turned out to be a hardware issue.  What I didn't do was solder the pins of the Raspberry PI and MegaPi.  You need to do this, otherwise you'll get flaky serial connection. 

To confirm you're having a similar issue, you can try connecting a USB cable between the two devices and use bot.start('/dev/ttyUSB0").  If that works, then you'll likely have a faulty connection too.
